#pragma once
#include <string>
#include <bsoncxx/document/value.hpp>
#include <bsoncxx/builder/stream/document.hpp>
#include <chrono>

struct CurrentLocation {
    std::string farmId;
    std::string barnId;
    std::string stallId;

    CurrentLocation(const std::string& farm = "N/A",
                    const std::string& barn = "N/A",
                    const std::string& stall = "N/A")
        : farmId(farm), barnId(barn), stallId(stall) {}
};

class Pig {
public:
    int pigId;
    std::string tag;
    std::string breed;
    int age;
    CurrentLocation currentLocation;
   
    // 🧠 Full constructor for manual creation
    Pig(int pig_id,
        const std::string& tag,
        const std::string& breed,
        int age,
        const CurrentLocation& location)
        : pigId(pig_id), tag(tag), breed(breed), age(age), currentLocation(location) {}

    // 🧠 Quick constructor with autogenerated tag and default values
    Pig(int pig_id)
        : pigId(pig_id),
          tag("Tag-" + std::string((pig_id < 10 ? "00" : (pig_id < 100 ? "0" : ""))) + std::to_string(pig_id)),
          breed("UNKNOWN"),
          age(0),
          currentLocation("UNKNOWN_FARM", "UNKNOWN_BARN", "UNKNOWN_STALL") {}
    bsoncxx::document::value to_bson() const;
};
